package com.pkmngen.leaks;

import java.io.File;
import java.text.SimpleDateFormat;
import java.util.Collections;
import java.util.Date;
import java.util.Locale;
import kotlin.jvm.internal.DefaultConstructorMarker;
import kotlin.jvm.internal.Intrinsics;
import leakcanary.GcTrigger.Default;
import leakcanary.ObjectWatcher;
import leakcanary.OnObjectRetainedListener;
import org.jetbrains.annotations.NotNull;
import shark.HeapAnalysis;
import shark.HeapAnalyzer;
import shark.KeyedWeakReferenceFinder;
import shark.MetadataExtractor;
import shark.ObjectInspectors;

public final class JvmHeapAnalyzer implements OnObjectRetainedListener {
   @NotNull
   public static final Companion Companion = new Companion();

   private static final String DATE_PATTERN = "yyyy-MM-dd_HH-mm-ss_SSS'.hprof'";
   private final ObjectWatcher objectWatcher;
   private final SimpleDateFormat fileNameFormat = new SimpleDateFormat(DATE_PATTERN, Locale.US);

   public JvmHeapAnalyzer(@NotNull ObjectWatcher objectWatcher) {
      Intrinsics.checkNotNullParameter(objectWatcher, "objectWatcher");
      this.objectWatcher = objectWatcher;
   }

   @Override
   public void onObjectRetained() {
      Default.INSTANCE.runGc();
      if (objectWatcher.getRetainedObjectCount() == 0) {
         return;
      }

      File hprofFile = new File(fileNameFormat.format(new Date()));
      System.out.println("Dumping the heap to " + hprofFile.getAbsolutePath());
      HotSpotHeapDumper.INSTANCE.dumpHeap(hprofFile.getAbsolutePath());
      HeapAnalyzer analyzer = new HeapAnalyzer(step -> {
         Intrinsics.checkNotNullParameter(step, "step");
         System.out.println("Analysis in progress, working on: " + step.name());
      });
      // Explicit equivalents of the original Kotlin defaults (mask 100): empty
      // reference matchers, no metadata extractor, and no Proguard mapping.
      HeapAnalysis heapDumpAnalysis = analyzer.analyze(
         hprofFile, KeyedWeakReferenceFinder.INSTANCE, Collections.emptyList(), true,
         ObjectInspectors.Companion.getJdkDefaults(), MetadataExtractor.Companion.getNO_OP(), null
      );
      System.out.println(heapDumpAnalysis);
   }

   public static final class Companion {
      private Companion() {
      }

      // Preserve the public constructor generated by the Kotlin compiler.
      public Companion(DefaultConstructorMarker ignored) {
         this();
      }
   }
}
