#!/usr/bin/env python3
"""Write a reproducible material/biome/runtime coverage inventory, without claiming visual QA."""
import argparse
from collections import Counter
import json
from pathlib import Path
import re

from PIL import Image

from prepare_stardew_presentation import ROOT, OUTPUT, digest


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--write-docs", action="store_true", help="Update tracked ASSET-COVERAGE.md explicitly")
    args = parser.parse_args()
    metadata = json.loads((OUTPUT / 'world-atlas.json').read_text(encoding='utf-8'))
    provenance = json.loads((OUTPUT / 'PROVENANCE.json').read_text(encoding='utf-8'))
    profiles = json.loads((ROOT / 'resources/visual/biomes/profiles.json').read_text(encoding='utf-8'))['profiles']
    atlas = Image.open(OUTPUT / 'world-atlas.png').convert('RGBA')
    regions = metadata['regions']
    assert provenance['atlasSha256'] == digest(OUTPUT / 'world-atlas.png')
    assert provenance['metadataSha256'] == digest(OUTPUT / 'world-atlas.json')
    def origin(key):
        record = provenance['regions'][key]
        return origin(record['aliasOf']) if 'aliasOf' in record else record
    def status(key):
        p = origin(key)
        return 'retained-special' if 'retainedCompatibility' in p else 'covered-reference' if 'source' in p else 'retained-landscape'
    usages = {key: [] for key in regions}
    for path in sorted((ROOT / 'src/com/pkmngen/game').rglob('*.java')):
        for number, line in enumerate(path.read_text(encoding='utf-8').splitlines(), 1):
            for literal in set(re.findall(r'"([a-zA-Z0-9_]+)"', line)) & regions.keys():
                usages[literal].append(f'{path.name}:{number}')
    frames = {}
    for animation, sequence in metadata['animations'].items():
        assert sequence['fps'] > 0 and sequence['frames']
        for index, frame in enumerate(sequence['frames']):
            assert frame in regions, (animation, frame)
            frames.setdefault(frame, []).append(f'{animation}[{index}]')
    for name, r in regions.items():
        x, y, w, h = (r[key] for key in ('x', 'y', 'width', 'height'))
        assert min(x, y) >= 2 and min(w, h) > 0 and x+w+2 <= atlas.width and y+h+2 <= atlas.height, name
        alpha = atlas.crop((x, y, x+w, y+h)).getchannel('A')
        assert alpha.getbbox(), name
        if r.get('kind') == 'surface':
            assert alpha.getextrema() == (255, 255), name
        for coordinate, extent in [('anchorX', w), ('anchorY', h)]:
            assert 0 <= r.get(coordinate, 0) <= extent, (name, coordinate)
    for profile in profiles.values():
        for section in ('terrain', 'cliff', 'fluid', 'decor'):
            for material in profile[section].values():
                assert material in regions, material
    counts = Counter(status(key) for key in regions)
    lines = [
        '# Asset coverage — recovered presentation', '',
        'Generated by `python tools/audit_stardew_assets.py`; regenerate after changing the atlas or runtime audit.', '',
        f'Atlas: **{len(regions)} regions**, **{len(metadata["animations"])} animations**, **{len(profiles)} biome profiles**. '
        + '; '.join(f'{key}: {value}' for key, value in sorted(counts.items())) + '.', '',
        f'Atlas SHA-256: `{provenance["atlasSha256"]}`. Metadata SHA-256: `{provenance["metadataSha256"]}`.', '',
        '## Loading precedence and scope', '',
        '`BwAssets` loads the generated Stardew atlas (which explicitly retains the landscape regions listed below), '
        'then trainer-only Unova regions, then optional custom overrides. Retained landscape artwork remains a declared '
        'temporary dependency; it is not represented as newly acquired Stardew art. The independent PMD Pokémon atlas remains unchanged.', '',
        'Coverage means a material resolves with valid bounds, nonempty pixels and declared source. It does **not** mean '
        'every gameplay identity or scene has been visually verified. `objectName` and `terrainName` contain dynamic mapping; '
        'the runtime inventory below exercises exact source-evidenced identities and reports all unresolved cases.', '',
        '## Contract and crop recovery', '',
        'Schema version 2 explicitly records source-pixel crops/samples, source-pixel anchors from left/bottom, world-unit '
        'sizes/offsets, two-pixel extrusion including atlas corners, and nearest filtering. Existing built-in pixel anchors '
        'remain pixel anchors; custom normalized anchors are not reinterpreted. Objects use their complete source canvas '
        'and one full-region sample. Source-origin preservation replaces alpha trimming. Dimensions preserve source aspect ratio.', '',
        'The old wall crop included the wallpaper sheet’s three-row cast shadow (alpha 101/55/20). The real opaque face '
        'and baseboard occupy 16×45 pixels. Both wall regions now retain precisely that face; opacity validation remains enabled. '
        '`wall_wood` now selects wood wallpaper instead of the ocean illustration. Bed/trunk/cactus/stalagmite crops contain '
        'complete individual objects. The previous wardrobe crop was a door, so the real landscape wardrobe is explicitly retained.', '',
        'The compatibility chimney preserves the original upstream construction icon, including its unusual palette; '
        'it is declared `retained-special`, not approved as finished Stardew artwork. Missing legacy Entei/Raikou/Suicune '
        'Tile paths are supplied by complete species-specific PMD miniatures in `resources/pokemon`; provenance records '
        'the exact original frame/hash and transformation. Modern Pokémon continue to use their unchanged PMD sheets.', '',
        'Sources/rights: `art-source/reference/manifest.json`, `art-source/compatibility/manifest.json`, '
        '`resources/visual/stardew/PROVENANCE.json`, and `resources/pokemon/PMD-COMPATIBILITY.json`. '
        'Downloads/credits do not establish redistribution permission. See the project rights review before distribution.', '',
        'Verification: `python tools/test_stardew_assets.py` checks the failure’s actual alpha pixels, complete furniture/rocks, '
        'whole object samples, aspect ratios, tree isolation, all source/frame bounds, edge/corner padding, strict changed-input '
        'rejection, and deterministic output bytes. Native scene screenshots are separate evidence in `REWORK-TESTS.md`.', '',
        '## Biome material roles', '',
        '| Biome | Role | Material | Status |', '|---|---|---|---|',
    ]
    for biome, profile in sorted(profiles.items()):
        for section in ('terrain', 'cliff', 'fluid', 'decor'):
            for role, key in sorted(profile[section].items()):
                lines.append(f'| {biome} | {section}.{role} | `{key}` | {status(key)} |')
    lines.extend(['', '## Complete generated material inventory', '',
        'Collision remains the original `Tile` flags, independent of pixel dimensions; this pipeline does not change collision. '
        '`renderer` dimensions preserve the existing consumer fallback; explicit dimensions are world units. '
        'Static references list up to three exact source string occurrences, not proof that a branch executes.', '',
        '| Material | Status | Source crop (x,y,w,h) / retained region | Canvas | Sample | World size | Frame role | Java references |',
        '|---|---|---|---|---|---|---|---|'])
    for key, r in sorted(regions.items()):
        p = origin(key)
        source = f'{p["source"]}: {p["crop"]}' if 'source' in p else p['retainedFrom'] + '#' + p['region']
        sample = f'{r["sampleWidth"]}×{r["sampleHeight"]}' if 'sampleWidth' in r else 'legacy grid / named full region'
        world = f'{r["worldWidth"]:.3g}×{r["worldHeight"]:.3g}' if 'worldWidth' in r else 'renderer'
        role = ', '.join(frames.get(key, [])) or ('animation alias' if key in metadata['animations'] else 'static')
        lines.append(f'| `{key}` | {status(key)} | {source} | {r["width"]}×{r["height"]} | {sample} | {world} | {role} | {", ".join(usages[key][:3])} |')
    runtime = ROOT / 'build/asset-audit/asset-coverage-runtime.json'
    lines.extend(['', '## Actual Tile catalog audit', ''])
    if runtime.exists():
        result = json.loads(runtime.read_text(encoding='utf-8'))
        lines.extend([f'Tested JAR SHA-256: `{result["jarSha256"]}`. '
                      f'{int(result["tested"])} Tile instances constructed; {int(result["constructionErrors"])} construction errors; '
                      f'{int(result["missingMaterials"])} missing materials; {int(result["unclassifiedSolidObjects"])} unclassified solid objects; '
                      f'{int(result.get("sourceWarnings", 0))} source warnings.', '',
                      'Run `python tools/asset_coverage_test.py` against the final rebuilt JAR, then regenerate this document. '
                      'The test compiles only its harness; all `Tile`, collision and mapping behavior comes from that JAR. '
                      'Source warning capture includes TextureCache fallback exceptions even when construction returns normally.', '',
                      '| Input ground / upper | Resolved terrain / object | Solid / water / ledge | Status |',
                      '|---|---|---|---|'])
        for row in result['rows']:
            label = row['status'] + ('; source warning' if 'sourceWarning' in row else '')
            lines.append(f'| `{row["inputGround"]}` / `{row["inputUpper"]}` | `{row.get("terrain", "error")}` / `{row.get("object") or "—"}` | '
                         f'{row.get("solid", "?")} / {row.get("water", "?")} / {row.get("ledge", "?")} | {label} |')
        lines.extend(['', 'Dynamic name fragments are not an exhaustive identity enumeration: ' + ', '.join('`' + value.replace('|', '\\|') + '`' for value in result['dynamicNameFragmentsNotExhaustivelyEnumerated']) + '.',
                      'Generated suffix combinations, mods and scripted combinations require their own scene fixtures; they are not silently counted as passed.'])
    else:
        lines.append('Not yet run: `python tools/asset_coverage_test.py`. No complete Tile identity coverage is claimed.')
    destination = ROOT / ('docs/ASSET-COVERAGE.md' if args.write_docs else 'build/asset-audit/ASSET-COVERAGE.md')
    destination.parent.mkdir(parents=True, exist_ok=True)
    destination.write_text('\n'.join(lines) + '\n', encoding='utf-8', newline='\n')
    print('Material coverage verified and documented:', destination, dict(counts))


if __name__ == '__main__':
    main()
